# Generated by Django 5.1.3 on 2024-11-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='handy',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
