# Generated by Django 5.1.3 on 2024-11-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('subtasks', models.CharField(max_length=50)),
            ],
        ),
    ]
